name: trustworthy_ai_protein_engineering
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - biopython
  - pyyaml
  - tqdm
  - requests
  - matplotlib
  - seaborn
  - torch
  - pip
  - pip:
      - esm
