from typing import Dict, Any, Callable, List


class ScoringEngine:
    """
    Applies scoring functions to mutations generated by the MutationGenerator.
    Scoring functions can be ESM-based, structural, industrial, or custom.
    """

    def __init__(self):
        self.scorers = {}

    def register_scorer(self, name: str, fn: Callable[[Dict[str, Any]], float]):
        """
        Register a scoring function.

        Parameters
        ----------
        name : str
            Name of the scoring function.
        fn : Callable
            Function that takes a mutation dict and returns a float score.
        """
        self.scorers[name] = fn

    def score_mutation(self, mutation: Dict[str, Any]) -> Dict[str, Any]:
        """
        Apply all registered scoring functions to a single mutation.
        Returns a dict with scores added.
        """
        result = mutation.copy()
        for name, fn in self.scorers.items():
            result[f"score_{name}"] = fn(mutation)
        return result

    def score_mutations(self, mutations: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Apply all scoring functions to a list of mutations.
        """
        return [self.score_mutation(m) for m in mutations]

